package com.jpmorga.tradeprocess;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.io.IOException;
import java.util.Collection;
import java.util.List;

import org.junit.Test;

import com.jpmorgan.tradesettlement.TradeSettlementReport;
import com.jpmorgan.tradesettlement.domain.ReportData;

public class TradeProcessReportTest {

	/**
	 * Generate report based on the settlement date.
	 * settlement date = 02 Jan 2016 data is available in the instructions.txt. 
	 * however logic is build by assuming the settlement date will be updated based on the business scenario and 
	 * then the report will be generated by using updated settlement date.
	 * since the settlement date 02 Jan 2016 falls on non-business day, it will be updated to 04 Jan 2016.
	 * so the report is empty for 02 Jan 2016.
	 * @throws IOException
	 */
	@Test
	public void testReportNoData() throws IOException {
		TradeSettlementReport tp = new TradeSettlementReport();
		
		Collection<ReportData> report = tp.generateReport("02 Jan 2016");
		assertNotNull(report);
		assertEquals(0, report.size());
	}
	
	/**
	 * Generate report with settlement date = 04 Jan 2016.
	 * expected - 2 records
	 * foo will rank 1 based on outgoing amount.
	 * @throws IOException
	 */
	@Test
	public void testValidReport() throws IOException {
		TradeSettlementReport tp = new TradeSettlementReport();
		
		List<ReportData> report = tp.generateReport("04 Jan 2016");
		assertNotNull(report);
		assertEquals(2, report.size());
		assertNotNull(report.get(0));
		assertEquals(1, report.get(0).getRanking());
	}
	
	/**
	 * when no date is given as an input. it prints the valid business message instructing the unser to input the valid date in specified format.
	 * @throws IOException
	 */
	@Test
	public void testInValidReportInput() throws IOException {
		TradeSettlementReport tp = new TradeSettlementReport();
		
		List<ReportData> report = tp.generateReport("");
		assertNull(report);
	}
	
	/**
	 * when no date is given as an input. it prints the valid business message instructing the unser to input the valid date in specified format.
	 * @throws IOException
	 */
	@Test
	public void testInValidReportNullInput() throws IOException {
		TradeSettlementReport tp = new TradeSettlementReport();
		
		List<ReportData> report = tp.generateReport(null);
		assertNull(report);
	}
}
